### ISSUE TITLE
Validation failed exception

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-github-issues-prs#1]
I've tried to use the extension for the repository https://github.com/Microsoft/vscode-npm-scripts/issues, but I'm getting the exception below. Do I need to have a GITHUB access token in my environment?

```
{"message":"Validation Failed","errors":[{"message":"The listed users cannot be searched either because the users do not exist or you do not have permission to view the users.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/search/"}
e.doShow @ /C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
```

**Comment by chrmarti** [comment]
It doesn't need a token/password, the username is picked from 'git credential'. What is the output of `git remote -v`? And what is the output of `echo "url=https://github.com/Microsoft/vscode-npm-scripts.git\n\n" | git credential fill | grep username`?

**Comment by egamma** [comment]
I'm doing this on Windows.

```
git remote -v
origin  https://github.com/Microsoft/vscode-npm-scripts.git (fetch)
origin  https://github.com/Microsoft/vscode-npm-scripts.git (push)
```
git credential fill
url=https://github.com/Microsoft/vscode-npm-scripts.git

warning: invalid credential line:
```

**Comment by chrmarti** [comment]
@egamma A variation that works on Windows, could you check what the output is: `echo url=https://github.com/Microsoft/vscode-npm-scripts.git | git credential fill`

**Comment by egamma** [comment]
voila
```
echo url=https://github.com/Microsoft/vscode-npm-scripts.git | git credential fill
protocol=https
host=github.com
path=
username=Personal Access Token
password=xxxx
```

**Comment by chrmarti** [comment]
Fixed and added a setting `github.username` for when the username in the Git credentials manager cannot be used.
