### ISSUE TITLE
SSH connection issues

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode-github-issues-prs#12]
I get the following error working with the following remotes:
```
origin  git@github.com:Microsoft/vscode.git (fetch)
origin  git@github.com:Microsoft/vscode.git (push)
```

![screen shot 2017-07-07 at 3 59 26 pm](https://user-images.githubusercontent.com/4674940/27979784-60d5957e-632d-11e7-99a5-1f17fba99b3c.png)

**Comment by chrmarti** [comment]
Could you try setting `"github.username"` to your GitHub username?

**Comment by kieferrm** [comment]
Done. Works for me.
