### ISSUE TITLE
discussion: what would it take to make this work with enterprise github?

### ISSUE THREAD

**Issue by mikehaas763** [Microsoft/vscode-github-issues-prs#25]
This would be really useful in an enterprise environment like mine where we have our own enterprise instance of github

what would it take to make this work with enterprise github?

**Comment by chrmarti** [comment]
If the remote URL can be used to derive the GHE URL, we could generalize the code here: https://github.com/Microsoft/vscode-github-issues-prs/blob/master/src/github-issues-prs.ts#L358

We use the GitHub NPM module which supports GHE as the example in its README shows: https://github.com/mikedeboer/node-github

Not sure what a good strategy is to decide whether or not to try to connect to a URL as GHE. Maybe ask the user the first time.

**Comment by chrmarti** [comment]
@mikehaas763 Do you have access to a GHE install? @Ikuyadeu is working on this in #27 and would need some help with testing it.

**Comment by mikehaas763** [comment]
@chrmarti Yes I do at work

**Comment by chrmarti** [comment]
@mikehaas763 I think #27 is ready for testing, could you give it a try?

**Comment by mikehaas763** [comment]
@chrmarti yes I'll try it out right now

**Comment by chrmarti** [comment]
@mikehaas763 I have published @Ikuyadeu's change with the setting hidden. Could you update the extension to the latest version 0.8.0 and set `"github.host"` to your GHE host for testing? (You can ignore the settings editor complaining about the setting being unknown.)

**Comment by pdavis77** [comment]
worked for me - using fqdn
thx!

**Comment by mikehaas763** [comment]
@chrmarti it worked for me as well!

**Comment by chrmarti** [comment]
Republished with the setting revealed. Thanks @Ikuyadeu for the PR!
