### ISSUE TITLE
Existence of explorer panel seems hit and miss

### ISSUE THREAD

**Issue by mungojam** [Microsoft/vscode-github-issues-prs#36]
I haven't worked out the trick yet, sometimes the GitHub Issues and PRs panel is there and sometimes it isn't. 

I've checked the remote for the folder I'm opening and it's pointing correctly at GitHub.

We use GitHub enterprise, and so I have set the `github.host` setting. I've also set the `github.username` setting because we have private repositories. I'm on Windows and the git credential manager is all set up.

I've checked the developer tools and there is no log there for this extension and nothing notable in the VS Code log either.

On past occasions I think reopening the folder worked or restarting VS Code, but right at the moment nothing is making it show up.

VS Code 1.22.2
extension 0.9.0

**Comment by chrmarti** [comment]
Is `GitHub Issues and PRs` checked in the context menu on the `Explorer` title of the file explorer?

**Comment by chrmarti** [comment]
![image](https://user-images.githubusercontent.com/9205389/41660778-4f865a9c-749d-11e8-94bd-04aa22a2df5d.png)

**Comment by mungojam** [comment]
Aha! It wasn't. And when I tick it, it now shows up for any project I open.

I don't really understand how it had got unticked unless it was when I tried reinstalling the extension before I fixed my remote or something like that.

Happy to close I guess unless there is some idea this has sparked off to make this all clearer?

**Comment by chrmarti** [comment]
There might be an issue tracking that this is hard to discover in the VS Code repo. The team is aware of it.
