### ISSUE TITLE
Only pulls one Milestone & its issues

### ISSUE THREAD

**Issue by steveAllen0112** [Microsoft/vscode-github-issues-prs#4]
I have several milestones, with a few open issues each, in my private repo.  This plugin is only pulling one of the milestones, and the issues under it.

**Comment by chrmarti** [comment]
It should currently show the next two upcoming (determined by their due dates) milestones.

**Comment by steveAllen0112** [comment]
I see.  And it's only showing the one b/c that's the only one that has a due date at all.

Are you planning on implementing the ability to see a) issues that don't have a milestone, and b) milestones that don't have a due date, and c) more than the first 2 w/ due dates?

**Comment by chrmarti** [comment]
Yes, I think that makes sense. I'll use this issue to track that feature request.
